### ISSUE TITLE
Color Scheme

### ISSUE THREAD

**Issue by mordocai** [codergirlstl/WeeLoveMusic#1]
The color scheme should be at least discussed, and possibly completely changed.

Pure black backgrounds are generally considered bad, and bright red on top of it more so. My understanding is these were pulled from the logo but in my opinion that logo will fit in a variety of color schemes.

The easiest way would be to set up a time to discuss this in person.

**Comment by codergirlstl** [comment]
Cool. I also will play around with some other color schemes.

**Comment by codergirlstl** [comment]
Hi Chris,

Could we get together to talk about the website this week?

I am free Tuesday evening or if there is another time this weekend I am pretty free as well.

Thank you,

Sheila

**Comment by mordocai** [comment]
Tuesday evening should work. I'll send you my phone number via email so we can figure out when/where.
