### ISSUE TITLE
Consider using bootstrap for theming/layout of web site

### ISSUE THREAD

**Issue by mordocai** [codergirlstl/WeeLoveMusic#2]
Something to consider, is to use bootstrap http://getbootstrap.com/ to base your web page on.

Some of the benefits include:

1. Prebuilt themes which include good color schemes are available.
2. Mostly automatic support for mobile
3. Mostly automatic support for a unified look across multiple browsers (currently your website looks very slightly different in chrome compared to firefox, for instance)
4. Prebuilt css classes for layout

The primary disadvantages are:

1. Uses some javascript, which your page currently doesn't require.
2. Can take a bit of work to setup (though shouldn't be too bad)
3. Is currently larger than your entire site combined

**Comment by codergirlstl** [comment]
Yes that is a great suggestion. I was planning on adding javascript so that is ok. Also I can add more material to the pages, I am still getting the class info and bio together.
