### ISSUE TITLE
Discuss hosting options

### ISSUE THREAD

**Issue by mordocai** [codergirlstl/WeeLoveMusic#7]
This is just an issue to discuss how the site will be hosted.

Current thoughts:

1. Github pages: https://pages.github.com/. We can redirect her domain name to github pages. It is free and super simple to use.
2. Bitballoon: https://www.bitballoon.com/. Looks really easy to use and is only $5 a month.
3. Static site hosting with amazon. http://docs.aws.amazon.com/gettingstarted/latest/swh/website-hosting-intro.html. This is complicated to setup and I'd probably prefer one of the above options. However, it is very cheap/free as well depending on how much traffic the site gets (which will almost certainly stay free).
4. My server. This would be best for a temporary solution as I like to play around with my server so 100% uptime is not guaranteed. It would be free unless she starts getting a ton of traffic though.

All of these will require you or someone else technically inclined to change the web page. I would not expect a normal computer user to be able to make changes with any of these methods, as they would have to edit HTML themselves as well as know how to push the changes through git or other methods.

If a goal is for her to be able to edit the website herself, I would recommend a hosted CMS(https://en.wikipedia.org/wiki/Content_management_system). PRETTY MUCH ALL HOSTED CMS WILL REQUIRE YOU TO THROW ALL YOUR CURRENT WORK AWAY. However, it'll be considerably easier for a non-tech person to manage.

* Wordpress (https://wordpress.com/). Hosting with a domain is $13 a year (one of the cheapest options).

* Weebly (http://www.weebly.com/) Hosting with a domain is $4 a month.

* ... There's a lot of these. Google hosted CMS and take a look.

**Comment by codergirlstl** [comment]
I think Bitballoon sounds the best of those options. I think can edit the website. It would be updated a few times a year when the class dates changed every semester. I will talk to he about it.
